version: '3.7'

services:
  web:
    image: 'node:12-alpine'
    volumes:
      - './:/app'
    working_dir: '/app'
    environment:
      HOST: '0.0.0.0'
    ports:
      - '3000:3000'
    command: sh -c 'npm install && npm run dev'
